// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Action struct {
	ID             string             `json:"id"`
	Capability     string             `json:"capability"`
	Payload        []byte             `json:"payload"`
	CallerType     string             `json:"caller_type"`
	CallerID       string             `json:"caller_id"`
	CallerName     string             `json:"caller_name"`
	Scope          []string           `json:"scope"`
	IdempotencyKey string             `json:"idempotency_key"`
	Status         string             `json:"status"`
	Result         []byte             `json:"result"`
	Error          []byte             `json:"error"`
	PolicyDecision []byte             `json:"policy_decision"`
	ExecutedAt     pgtype.Timestamptz `json:"executed_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type AuditEvent struct {
	ID         string             `json:"id"`
	ActionID   string             `json:"action_id"`
	Kind       string             `json:"kind"`
	Capability string             `json:"capability"`
	CallerType string             `json:"caller_type"`
	Detail     []byte             `json:"detail"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Capability struct {
	Name         string             `json:"name"`
	Description  pgtype.Text        `json:"description"`
	InputSchema  []byte             `json:"input_schema"`
	OutputSchema []byte             `json:"output_schema"`
	Permissions  []string           `json:"permissions"`
	Simulatable  bool               `json:"simulatable"`
	Idempotent   bool               `json:"idempotent"`
	RegisteredAt pgtype.Timestamptz `json:"registered_at"`
}

type IdempotencyKey struct {
	Key       string             `json:"key"`
	ActionID  string             `json:"action_id"`
	Result    []byte             `json:"result"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type OutcomeOutbox struct {
	ID          string             `json:"id"`
	ActionID    string             `json:"action_id"`
	Payload     []byte             `json:"payload"`
	Attempts    int32              `json:"attempts"`
	NextAttempt pgtype.Timestamptz `json:"next_attempt"`
	DeliveredAt pgtype.Timestamptz `json:"delivered_at"`
	LastError   pgtype.Text        `json:"last_error"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type PolicyRule struct {
	ID         string             `json:"id"`
	Capability pgtype.Text        `json:"capability"`
	CallerType pgtype.Text        `json:"caller_type"`
	Scope      []string           `json:"scope"`
	Decision   string             `json:"decision"`
	Reason     pgtype.Text        `json:"reason"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}
