// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendAuditEvent = `-- name: AppendAuditEvent :exec
INSERT INTO audit_events (id, action_id, kind, capability, caller_type, org_id, team_id, detail, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type AppendAuditEventParams struct {
	ID         string             `json:"id"`
	ActionID   string             `json:"action_id"`
	Kind       string             `json:"kind"`
	Capability string             `json:"capability"`
	CallerType string             `json:"caller_type"`
	OrgID      string             `json:"org_id"`
	TeamID     string             `json:"team_id"`
	Detail     []byte             `json:"detail"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) AppendAuditEvent(ctx context.Context, arg AppendAuditEventParams) error {
	_, err := q.db.Exec(ctx, appendAuditEvent,
		arg.ID,
		arg.ActionID,
		arg.Kind,
		arg.Capability,
		arg.CallerType,
		arg.OrgID,
		arg.TeamID,
		arg.Detail,
		arg.CreatedAt,
	)
	return err
}

const bumpOutcomeAttempt = `-- name: BumpOutcomeAttempt :exec
UPDATE outcome_outbox SET attempts = attempts + 1, next_attempt = $1, last_error = $2 WHERE id = $3
`

type BumpOutcomeAttemptParams struct {
	NextAttempt pgtype.Timestamptz `json:"next_attempt"`
	LastError   pgtype.Text        `json:"last_error"`
	ID          string             `json:"id"`
}

func (q *Queries) BumpOutcomeAttempt(ctx context.Context, arg BumpOutcomeAttemptParams) error {
	_, err := q.db.Exec(ctx, bumpOutcomeAttempt, arg.NextAttempt, arg.LastError, arg.ID)
	return err
}

const deletePolicyRule = `-- name: DeletePolicyRule :exec
DELETE FROM policy_rules WHERE id = $1
`

func (q *Queries) DeletePolicyRule(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePolicyRule, id)
	return err
}

const enqueueOutcome = `-- name: EnqueueOutcome :exec
INSERT INTO outcome_outbox (id, action_id, payload, attempts, next_attempt, delivered_at, last_error, created_at)
VALUES ($1, $2, $3, 0, $4, NULL, NULL, $5)
`

type EnqueueOutcomeParams struct {
	ID          string             `json:"id"`
	ActionID    string             `json:"action_id"`
	Payload     []byte             `json:"payload"`
	NextAttempt pgtype.Timestamptz `json:"next_attempt"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) EnqueueOutcome(ctx context.Context, arg EnqueueOutcomeParams) error {
	_, err := q.db.Exec(ctx, enqueueOutcome,
		arg.ID,
		arg.ActionID,
		arg.Payload,
		arg.NextAttempt,
		arg.CreatedAt,
	)
	return err
}

const getAction = `-- name: GetAction :one
SELECT id, capability, payload, caller_type, caller_id, caller_name, scope, idempotency_key, status, mode, result, error, policy_decision, executed_at, completed_at, created_at, updated_at
FROM actions WHERE id = $1
`

type GetActionRow struct {
	ID             string             `json:"id"`
	Capability     string             `json:"capability"`
	Payload        []byte             `json:"payload"`
	CallerType     string             `json:"caller_type"`
	CallerID       string             `json:"caller_id"`
	CallerName     string             `json:"caller_name"`
	Scope          []string           `json:"scope"`
	IdempotencyKey string             `json:"idempotency_key"`
	Status         string             `json:"status"`
	Mode           string             `json:"mode"`
	Result         []byte             `json:"result"`
	Error          []byte             `json:"error"`
	PolicyDecision []byte             `json:"policy_decision"`
	ExecutedAt     pgtype.Timestamptz `json:"executed_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetAction(ctx context.Context, id string) (GetActionRow, error) {
	row := q.db.QueryRow(ctx, getAction, id)
	var i GetActionRow
	err := row.Scan(
		&i.ID,
		&i.Capability,
		&i.Payload,
		&i.CallerType,
		&i.CallerID,
		&i.CallerName,
		&i.Scope,
		&i.IdempotencyKey,
		&i.Status,
		&i.Mode,
		&i.Result,
		&i.Error,
		&i.PolicyDecision,
		&i.ExecutedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCapability = `-- name: GetCapability :one
SELECT name, description, input_schema, output_schema, permissions, simulatable, idempotent, registered_at
FROM capabilities WHERE name = $1
`

func (q *Queries) GetCapability(ctx context.Context, name string) (Capability, error) {
	row := q.db.QueryRow(ctx, getCapability, name)
	var i Capability
	err := row.Scan(
		&i.Name,
		&i.Description,
		&i.InputSchema,
		&i.OutputSchema,
		&i.Permissions,
		&i.Simulatable,
		&i.Idempotent,
		&i.RegisteredAt,
	)
	return i, err
}

const listActionsPaged = `-- name: ListActionsPaged :many
SELECT id, capability, payload, caller_type, caller_id, caller_name, scope, idempotency_key, status, mode, result, error, policy_decision, executed_at, completed_at, created_at, updated_at
FROM actions
ORDER BY created_at DESC
LIMIT $1
`

type ListActionsPagedRow struct {
	ID             string             `json:"id"`
	Capability     string             `json:"capability"`
	Payload        []byte             `json:"payload"`
	CallerType     string             `json:"caller_type"`
	CallerID       string             `json:"caller_id"`
	CallerName     string             `json:"caller_name"`
	Scope          []string           `json:"scope"`
	IdempotencyKey string             `json:"idempotency_key"`
	Status         string             `json:"status"`
	Mode           string             `json:"mode"`
	Result         []byte             `json:"result"`
	Error          []byte             `json:"error"`
	PolicyDecision []byte             `json:"policy_decision"`
	ExecutedAt     pgtype.Timestamptz `json:"executed_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListActionsPaged(ctx context.Context, limit int32) ([]ListActionsPagedRow, error) {
	rows, err := q.db.Query(ctx, listActionsPaged, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActionsPagedRow
	for rows.Next() {
		var i ListActionsPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.Capability,
			&i.Payload,
			&i.CallerType,
			&i.CallerID,
			&i.CallerName,
			&i.Scope,
			&i.IdempotencyKey,
			&i.Status,
			&i.Mode,
			&i.Result,
			&i.Error,
			&i.PolicyDecision,
			&i.ExecutedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditForAction = `-- name: ListAuditForAction :many
SELECT id, action_id, kind, capability, caller_type, org_id, team_id, detail, created_at
FROM audit_events WHERE action_id = $1 ORDER BY created_at
`

type ListAuditForActionRow struct {
	ID         string             `json:"id"`
	ActionID   string             `json:"action_id"`
	Kind       string             `json:"kind"`
	Capability string             `json:"capability"`
	CallerType string             `json:"caller_type"`
	OrgID      string             `json:"org_id"`
	TeamID     string             `json:"team_id"`
	Detail     []byte             `json:"detail"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAuditForAction(ctx context.Context, actionID string) ([]ListAuditForActionRow, error) {
	rows, err := q.db.Query(ctx, listAuditForAction, actionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditForActionRow
	for rows.Next() {
		var i ListAuditForActionRow
		if err := rows.Scan(
			&i.ID,
			&i.ActionID,
			&i.Kind,
			&i.Capability,
			&i.CallerType,
			&i.OrgID,
			&i.TeamID,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCapabilities = `-- name: ListCapabilities :many
SELECT name, description, input_schema, output_schema, permissions, simulatable, idempotent, registered_at
FROM capabilities
ORDER BY name
`

func (q *Queries) ListCapabilities(ctx context.Context) ([]Capability, error) {
	rows, err := q.db.Query(ctx, listCapabilities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Capability
	for rows.Next() {
		var i Capability
		if err := rows.Scan(
			&i.Name,
			&i.Description,
			&i.InputSchema,
			&i.OutputSchema,
			&i.Permissions,
			&i.Simulatable,
			&i.Idempotent,
			&i.RegisteredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingAsync = `-- name: ListPendingAsync :many
SELECT id, capability, payload, caller_type, caller_id, caller_name, scope, idempotency_key, status, mode, result, error, policy_decision, executed_at, completed_at, created_at, updated_at
FROM actions
WHERE mode = 'async' AND status = 'validated'
ORDER BY created_at
LIMIT $1
`

type ListPendingAsyncRow struct {
	ID             string             `json:"id"`
	Capability     string             `json:"capability"`
	Payload        []byte             `json:"payload"`
	CallerType     string             `json:"caller_type"`
	CallerID       string             `json:"caller_id"`
	CallerName     string             `json:"caller_name"`
	Scope          []string           `json:"scope"`
	IdempotencyKey string             `json:"idempotency_key"`
	Status         string             `json:"status"`
	Mode           string             `json:"mode"`
	Result         []byte             `json:"result"`
	Error          []byte             `json:"error"`
	PolicyDecision []byte             `json:"policy_decision"`
	ExecutedAt     pgtype.Timestamptz `json:"executed_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListPendingAsync(ctx context.Context, limit int32) ([]ListPendingAsyncRow, error) {
	rows, err := q.db.Query(ctx, listPendingAsync, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingAsyncRow
	for rows.Next() {
		var i ListPendingAsyncRow
		if err := rows.Scan(
			&i.ID,
			&i.Capability,
			&i.Payload,
			&i.CallerType,
			&i.CallerID,
			&i.CallerName,
			&i.Scope,
			&i.IdempotencyKey,
			&i.Status,
			&i.Mode,
			&i.Result,
			&i.Error,
			&i.PolicyDecision,
			&i.ExecutedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPolicyRules = `-- name: ListPolicyRules :many
SELECT id, capability, caller_type, scope, decision, reason, created_at, updated_at
FROM policy_rules
ORDER BY id
`

func (q *Queries) ListPolicyRules(ctx context.Context) ([]PolicyRule, error) {
	rows, err := q.db.Query(ctx, listPolicyRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PolicyRule
	for rows.Next() {
		var i PolicyRule
		if err := rows.Scan(
			&i.ID,
			&i.Capability,
			&i.CallerType,
			&i.Scope,
			&i.Decision,
			&i.Reason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupIdempotency = `-- name: LookupIdempotency :one
SELECT key, action_id, result, expires_at, created_at
FROM idempotency_keys WHERE key = $1
`

func (q *Queries) LookupIdempotency(ctx context.Context, key string) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, lookupIdempotency, key)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.ActionID,
		&i.Result,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const markOutcomeDelivered = `-- name: MarkOutcomeDelivered :exec
UPDATE outcome_outbox SET delivered_at = $1 WHERE id = $2
`

type MarkOutcomeDeliveredParams struct {
	DeliveredAt pgtype.Timestamptz `json:"delivered_at"`
	ID          string             `json:"id"`
}

func (q *Queries) MarkOutcomeDelivered(ctx context.Context, arg MarkOutcomeDeliveredParams) error {
	_, err := q.db.Exec(ctx, markOutcomeDelivered, arg.DeliveredAt, arg.ID)
	return err
}

const nextOutcomeBatch = `-- name: NextOutcomeBatch :many
SELECT id, action_id, payload, attempts, next_attempt, delivered_at, last_error, created_at
FROM outcome_outbox
WHERE delivered_at IS NULL AND next_attempt <= $1
ORDER BY next_attempt
LIMIT $2
`

type NextOutcomeBatchParams struct {
	NextAttempt pgtype.Timestamptz `json:"next_attempt"`
	Limit       int32              `json:"limit"`
}

func (q *Queries) NextOutcomeBatch(ctx context.Context, arg NextOutcomeBatchParams) ([]OutcomeOutbox, error) {
	rows, err := q.db.Query(ctx, nextOutcomeBatch, arg.NextAttempt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutcomeOutbox
	for rows.Next() {
		var i OutcomeOutbox
		if err := rows.Scan(
			&i.ID,
			&i.ActionID,
			&i.Payload,
			&i.Attempts,
			&i.NextAttempt,
			&i.DeliveredAt,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeAuditBefore = `-- name: PurgeAuditBefore :execrows
DELETE FROM audit_events
WHERE created_at < $1
  AND org_id = $2
`

type PurgeAuditBeforeParams struct {
	Before pgtype.Timestamptz `json:"before"`
	OrgID  string             `json:"org_id"`
}

func (q *Queries) PurgeAuditBefore(ctx context.Context, arg PurgeAuditBeforeParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeAuditBefore, arg.Before, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const putActionResult = `-- name: PutActionResult :exec
UPDATE actions SET status = $2, result = $3, error = $4, completed_at = $5, updated_at = $6 WHERE id = $1
`

type PutActionResultParams struct {
	ID          string             `json:"id"`
	Status      string             `json:"status"`
	Result      []byte             `json:"result"`
	Error       []byte             `json:"error"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) PutActionResult(ctx context.Context, arg PutActionResultParams) error {
	_, err := q.db.Exec(ctx, putActionResult,
		arg.ID,
		arg.Status,
		arg.Result,
		arg.Error,
		arg.CompletedAt,
		arg.UpdatedAt,
	)
	return err
}

const rememberIdempotency = `-- name: RememberIdempotency :exec
INSERT INTO idempotency_keys (key, action_id, result, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT(key) DO UPDATE SET
    action_id  = EXCLUDED.action_id,
    result     = EXCLUDED.result,
    expires_at = EXCLUDED.expires_at
`

type RememberIdempotencyParams struct {
	Key       string             `json:"key"`
	ActionID  string             `json:"action_id"`
	Result    []byte             `json:"result"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) RememberIdempotency(ctx context.Context, arg RememberIdempotencyParams) error {
	_, err := q.db.Exec(ctx, rememberIdempotency,
		arg.Key,
		arg.ActionID,
		arg.Result,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const searchAuditEvents = `-- name: SearchAuditEvents :many
SELECT id, action_id, kind, capability, caller_type, org_id, team_id, detail, created_at
FROM audit_events
WHERE ($1::TEXT       IS NULL OR capability  = $1)
  AND ($2::TEXT      IS NULL OR caller_type = $2)
  AND ($3::TEXT           IS NULL OR org_id      = $3)
  AND ($4::TIMESTAMPTZ   IS NULL OR created_at >= $4)
  AND ($5::TIMESTAMPTZ     IS NULL OR created_at <= $5)
ORDER BY created_at
`

type SearchAuditEventsParams struct {
	Capability pgtype.Text        `json:"capability"`
	CallerType pgtype.Text        `json:"caller_type"`
	OrgID      pgtype.Text        `json:"org_id"`
	FromTs     pgtype.Timestamptz `json:"from_ts"`
	ToTs       pgtype.Timestamptz `json:"to_ts"`
}

type SearchAuditEventsRow struct {
	ID         string             `json:"id"`
	ActionID   string             `json:"action_id"`
	Kind       string             `json:"kind"`
	Capability string             `json:"capability"`
	CallerType string             `json:"caller_type"`
	OrgID      string             `json:"org_id"`
	TeamID     string             `json:"team_id"`
	Detail     []byte             `json:"detail"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) SearchAuditEvents(ctx context.Context, arg SearchAuditEventsParams) ([]SearchAuditEventsRow, error) {
	rows, err := q.db.Query(ctx, searchAuditEvents,
		arg.Capability,
		arg.CallerType,
		arg.OrgID,
		arg.FromTs,
		arg.ToTs,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchAuditEventsRow
	for rows.Next() {
		var i SearchAuditEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.ActionID,
			&i.Kind,
			&i.Capability,
			&i.CallerType,
			&i.OrgID,
			&i.TeamID,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateActionStatus = `-- name: UpdateActionStatus :exec
UPDATE actions SET status = $2, updated_at = $3 WHERE id = $1
`

type UpdateActionStatusParams struct {
	ID        string             `json:"id"`
	Status    string             `json:"status"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateActionStatus(ctx context.Context, arg UpdateActionStatusParams) error {
	_, err := q.db.Exec(ctx, updateActionStatus, arg.ID, arg.Status, arg.UpdatedAt)
	return err
}

const upsertAction = `-- name: UpsertAction :exec
INSERT INTO actions (id, capability, payload, caller_type, caller_id, caller_name, scope, idempotency_key, status, mode, result, error, policy_decision, executed_at, completed_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
ON CONFLICT(id) DO UPDATE SET
    capability      = EXCLUDED.capability,
    payload         = EXCLUDED.payload,
    caller_type     = EXCLUDED.caller_type,
    caller_id       = EXCLUDED.caller_id,
    caller_name     = EXCLUDED.caller_name,
    scope           = EXCLUDED.scope,
    idempotency_key = EXCLUDED.idempotency_key,
    status          = EXCLUDED.status,
    mode            = EXCLUDED.mode,
    result          = EXCLUDED.result,
    error           = EXCLUDED.error,
    policy_decision = EXCLUDED.policy_decision,
    executed_at     = EXCLUDED.executed_at,
    completed_at    = EXCLUDED.completed_at,
    updated_at      = EXCLUDED.updated_at
`

type UpsertActionParams struct {
	ID             string             `json:"id"`
	Capability     string             `json:"capability"`
	Payload        []byte             `json:"payload"`
	CallerType     string             `json:"caller_type"`
	CallerID       string             `json:"caller_id"`
	CallerName     string             `json:"caller_name"`
	Scope          []string           `json:"scope"`
	IdempotencyKey string             `json:"idempotency_key"`
	Status         string             `json:"status"`
	Mode           string             `json:"mode"`
	Result         []byte             `json:"result"`
	Error          []byte             `json:"error"`
	PolicyDecision []byte             `json:"policy_decision"`
	ExecutedAt     pgtype.Timestamptz `json:"executed_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertAction(ctx context.Context, arg UpsertActionParams) error {
	_, err := q.db.Exec(ctx, upsertAction,
		arg.ID,
		arg.Capability,
		arg.Payload,
		arg.CallerType,
		arg.CallerID,
		arg.CallerName,
		arg.Scope,
		arg.IdempotencyKey,
		arg.Status,
		arg.Mode,
		arg.Result,
		arg.Error,
		arg.PolicyDecision,
		arg.ExecutedAt,
		arg.CompletedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertCapability = `-- name: UpsertCapability :exec
INSERT INTO capabilities (name, description, input_schema, output_schema, permissions, simulatable, idempotent, registered_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT(name) DO UPDATE SET
    description   = EXCLUDED.description,
    input_schema  = EXCLUDED.input_schema,
    output_schema = EXCLUDED.output_schema,
    permissions   = EXCLUDED.permissions,
    simulatable   = EXCLUDED.simulatable,
    idempotent    = EXCLUDED.idempotent,
    registered_at = EXCLUDED.registered_at
`

type UpsertCapabilityParams struct {
	Name         string             `json:"name"`
	Description  pgtype.Text        `json:"description"`
	InputSchema  []byte             `json:"input_schema"`
	OutputSchema []byte             `json:"output_schema"`
	Permissions  []string           `json:"permissions"`
	Simulatable  bool               `json:"simulatable"`
	Idempotent   bool               `json:"idempotent"`
	RegisteredAt pgtype.Timestamptz `json:"registered_at"`
}

func (q *Queries) UpsertCapability(ctx context.Context, arg UpsertCapabilityParams) error {
	_, err := q.db.Exec(ctx, upsertCapability,
		arg.Name,
		arg.Description,
		arg.InputSchema,
		arg.OutputSchema,
		arg.Permissions,
		arg.Simulatable,
		arg.Idempotent,
		arg.RegisteredAt,
	)
	return err
}

const upsertPolicyRule = `-- name: UpsertPolicyRule :exec
INSERT INTO policy_rules (id, capability, caller_type, scope, decision, reason, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT(id) DO UPDATE SET
    capability  = EXCLUDED.capability,
    caller_type = EXCLUDED.caller_type,
    scope       = EXCLUDED.scope,
    decision    = EXCLUDED.decision,
    reason      = EXCLUDED.reason,
    updated_at  = EXCLUDED.updated_at
`

type UpsertPolicyRuleParams struct {
	ID         string             `json:"id"`
	Capability pgtype.Text        `json:"capability"`
	CallerType pgtype.Text        `json:"caller_type"`
	Scope      []string           `json:"scope"`
	Decision   string             `json:"decision"`
	Reason     pgtype.Text        `json:"reason"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertPolicyRule(ctx context.Context, arg UpsertPolicyRuleParams) error {
	_, err := q.db.Exec(ctx, upsertPolicyRule,
		arg.ID,
		arg.Capability,
		arg.CallerType,
		arg.Scope,
		arg.Decision,
		arg.Reason,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
