// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"
)

type Querier interface {
	AppendAuditEvent(ctx context.Context, arg AppendAuditEventParams) error
	BumpOutcomeAttempt(ctx context.Context, arg BumpOutcomeAttemptParams) error
	DeletePolicyRule(ctx context.Context, id string) error
	EnqueueOutcome(ctx context.Context, arg EnqueueOutcomeParams) error
	GetAction(ctx context.Context, id string) (GetActionRow, error)
	GetCapability(ctx context.Context, name string) (Capability, error)
	ListActionsPaged(ctx context.Context, limit int32) ([]ListActionsPagedRow, error)
	ListAuditForAction(ctx context.Context, actionID string) ([]AuditEvent, error)
	ListCapabilities(ctx context.Context) ([]Capability, error)
	ListPendingAsync(ctx context.Context, limit int32) ([]ListPendingAsyncRow, error)
	ListPolicyRules(ctx context.Context) ([]PolicyRule, error)
	LookupIdempotency(ctx context.Context, key string) (IdempotencyKey, error)
	MarkOutcomeDelivered(ctx context.Context, arg MarkOutcomeDeliveredParams) error
	NextOutcomeBatch(ctx context.Context, arg NextOutcomeBatchParams) ([]OutcomeOutbox, error)
	PutActionResult(ctx context.Context, arg PutActionResultParams) error
	RememberIdempotency(ctx context.Context, arg RememberIdempotencyParams) error
	SearchAuditEvents(ctx context.Context, arg SearchAuditEventsParams) ([]AuditEvent, error)
	UpdateActionStatus(ctx context.Context, arg UpdateActionStatusParams) error
	UpsertAction(ctx context.Context, arg UpsertActionParams) error
	UpsertCapability(ctx context.Context, arg UpsertCapabilityParams) error
	UpsertPolicyRule(ctx context.Context, arg UpsertPolicyRuleParams) error
}

var _ Querier = (*Queries)(nil)
