// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql"
)

type Action struct {
	ID             string         `json:"id"`
	Capability     string         `json:"capability"`
	Payload        string         `json:"payload"`
	CallerType     string         `json:"caller_type"`
	CallerID       string         `json:"caller_id"`
	CallerName     string         `json:"caller_name"`
	Scope          string         `json:"scope"`
	IdempotencyKey string         `json:"idempotency_key"`
	Status         string         `json:"status"`
	Result         sql.NullString `json:"result"`
	Error          sql.NullString `json:"error"`
	PolicyDecision sql.NullString `json:"policy_decision"`
	ExecutedAt     sql.NullString `json:"executed_at"`
	CompletedAt    sql.NullString `json:"completed_at"`
	CreatedAt      string         `json:"created_at"`
	UpdatedAt      string         `json:"updated_at"`
	Mode           string         `json:"mode"`
}

type AuditEvent struct {
	ID         string `json:"id"`
	ActionID   string `json:"action_id"`
	Kind       string `json:"kind"`
	Capability string `json:"capability"`
	CallerType string `json:"caller_type"`
	Detail     string `json:"detail"`
	CreatedAt  string `json:"created_at"`
	OrgID      string `json:"org_id"`
	TeamID     string `json:"team_id"`
}

type Capability struct {
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	InputSchema  string         `json:"input_schema"`
	OutputSchema string         `json:"output_schema"`
	Permissions  string         `json:"permissions"`
	Simulatable  int64          `json:"simulatable"`
	Idempotent   int64          `json:"idempotent"`
	RegisteredAt string         `json:"registered_at"`
}

type IdempotencyKey struct {
	Key       string         `json:"key"`
	ActionID  string         `json:"action_id"`
	Result    string         `json:"result"`
	ExpiresAt sql.NullString `json:"expires_at"`
	CreatedAt string         `json:"created_at"`
}

type OutcomeOutbox struct {
	ID          string         `json:"id"`
	ActionID    string         `json:"action_id"`
	Payload     string         `json:"payload"`
	Attempts    int64          `json:"attempts"`
	NextAttempt string         `json:"next_attempt"`
	DeliveredAt sql.NullString `json:"delivered_at"`
	LastError   sql.NullString `json:"last_error"`
	CreatedAt   string         `json:"created_at"`
}

type PolicyRule struct {
	ID         string         `json:"id"`
	Capability sql.NullString `json:"capability"`
	CallerType sql.NullString `json:"caller_type"`
	Scope      string         `json:"scope"`
	Decision   string         `json:"decision"`
	Reason     sql.NullString `json:"reason"`
	CreatedAt  string         `json:"created_at"`
	UpdatedAt  string         `json:"updated_at"`
}
