// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const appendAuditEvent = `-- name: AppendAuditEvent :exec
INSERT INTO audit_events (id, action_id, kind, capability, caller_type, detail, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type AppendAuditEventParams struct {
	ID         string `json:"id"`
	ActionID   string `json:"action_id"`
	Kind       string `json:"kind"`
	Capability string `json:"capability"`
	CallerType string `json:"caller_type"`
	Detail     string `json:"detail"`
	CreatedAt  string `json:"created_at"`
}

func (q *Queries) AppendAuditEvent(ctx context.Context, arg AppendAuditEventParams) error {
	_, err := q.db.ExecContext(ctx, appendAuditEvent,
		arg.ID,
		arg.ActionID,
		arg.Kind,
		arg.Capability,
		arg.CallerType,
		arg.Detail,
		arg.CreatedAt,
	)
	return err
}

const bumpOutcomeAttempt = `-- name: BumpOutcomeAttempt :exec
UPDATE outcome_outbox SET attempts = attempts + 1, next_attempt = ?, last_error = ? WHERE id = ?
`

type BumpOutcomeAttemptParams struct {
	NextAttempt string         `json:"next_attempt"`
	LastError   sql.NullString `json:"last_error"`
	ID          string         `json:"id"`
}

func (q *Queries) BumpOutcomeAttempt(ctx context.Context, arg BumpOutcomeAttemptParams) error {
	_, err := q.db.ExecContext(ctx, bumpOutcomeAttempt, arg.NextAttempt, arg.LastError, arg.ID)
	return err
}

const deletePolicyRule = `-- name: DeletePolicyRule :exec
DELETE FROM policy_rules WHERE id = ?
`

func (q *Queries) DeletePolicyRule(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePolicyRule, id)
	return err
}

const enqueueOutcome = `-- name: EnqueueOutcome :exec
INSERT INTO outcome_outbox (id, action_id, payload, attempts, next_attempt, delivered_at, last_error, created_at)
VALUES (?, ?, ?, 0, ?, NULL, NULL, ?)
`

type EnqueueOutcomeParams struct {
	ID          string `json:"id"`
	ActionID    string `json:"action_id"`
	Payload     string `json:"payload"`
	NextAttempt string `json:"next_attempt"`
	CreatedAt   string `json:"created_at"`
}

func (q *Queries) EnqueueOutcome(ctx context.Context, arg EnqueueOutcomeParams) error {
	_, err := q.db.ExecContext(ctx, enqueueOutcome,
		arg.ID,
		arg.ActionID,
		arg.Payload,
		arg.NextAttempt,
		arg.CreatedAt,
	)
	return err
}

const getAction = `-- name: GetAction :one
SELECT id, capability, payload, caller_type, caller_id, caller_name, scope, idempotency_key, status, result, error, policy_decision, executed_at, completed_at, created_at, updated_at
FROM actions WHERE id = ?
`

func (q *Queries) GetAction(ctx context.Context, id string) (Action, error) {
	row := q.db.QueryRowContext(ctx, getAction, id)
	var i Action
	err := row.Scan(
		&i.ID,
		&i.Capability,
		&i.Payload,
		&i.CallerType,
		&i.CallerID,
		&i.CallerName,
		&i.Scope,
		&i.IdempotencyKey,
		&i.Status,
		&i.Result,
		&i.Error,
		&i.PolicyDecision,
		&i.ExecutedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCapability = `-- name: GetCapability :one
SELECT name, description, input_schema, output_schema, permissions, simulatable, idempotent, registered_at
FROM capabilities WHERE name = ?
`

func (q *Queries) GetCapability(ctx context.Context, name string) (Capability, error) {
	row := q.db.QueryRowContext(ctx, getCapability, name)
	var i Capability
	err := row.Scan(
		&i.Name,
		&i.Description,
		&i.InputSchema,
		&i.OutputSchema,
		&i.Permissions,
		&i.Simulatable,
		&i.Idempotent,
		&i.RegisteredAt,
	)
	return i, err
}

const listAuditForAction = `-- name: ListAuditForAction :many
SELECT id, action_id, kind, capability, caller_type, detail, created_at
FROM audit_events WHERE action_id = ? ORDER BY created_at
`

func (q *Queries) ListAuditForAction(ctx context.Context, actionID string) ([]AuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAuditForAction, actionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.ActionID,
			&i.Kind,
			&i.Capability,
			&i.CallerType,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCapabilities = `-- name: ListCapabilities :many
SELECT name, description, input_schema, output_schema, permissions, simulatable, idempotent, registered_at
FROM capabilities
ORDER BY name
`

func (q *Queries) ListCapabilities(ctx context.Context) ([]Capability, error) {
	rows, err := q.db.QueryContext(ctx, listCapabilities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Capability
	for rows.Next() {
		var i Capability
		if err := rows.Scan(
			&i.Name,
			&i.Description,
			&i.InputSchema,
			&i.OutputSchema,
			&i.Permissions,
			&i.Simulatable,
			&i.Idempotent,
			&i.RegisteredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPolicyRules = `-- name: ListPolicyRules :many
SELECT id, capability, caller_type, scope, decision, reason, created_at, updated_at
FROM policy_rules
ORDER BY id
`

func (q *Queries) ListPolicyRules(ctx context.Context) ([]PolicyRule, error) {
	rows, err := q.db.QueryContext(ctx, listPolicyRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PolicyRule
	for rows.Next() {
		var i PolicyRule
		if err := rows.Scan(
			&i.ID,
			&i.Capability,
			&i.CallerType,
			&i.Scope,
			&i.Decision,
			&i.Reason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupIdempotency = `-- name: LookupIdempotency :one
SELECT key, action_id, result, expires_at, created_at
FROM idempotency_keys WHERE key = ?
`

func (q *Queries) LookupIdempotency(ctx context.Context, key string) (IdempotencyKey, error) {
	row := q.db.QueryRowContext(ctx, lookupIdempotency, key)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.ActionID,
		&i.Result,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const markOutcomeDelivered = `-- name: MarkOutcomeDelivered :exec
UPDATE outcome_outbox SET delivered_at = ? WHERE id = ?
`

type MarkOutcomeDeliveredParams struct {
	DeliveredAt sql.NullString `json:"delivered_at"`
	ID          string         `json:"id"`
}

func (q *Queries) MarkOutcomeDelivered(ctx context.Context, arg MarkOutcomeDeliveredParams) error {
	_, err := q.db.ExecContext(ctx, markOutcomeDelivered, arg.DeliveredAt, arg.ID)
	return err
}

const nextOutcomeBatch = `-- name: NextOutcomeBatch :many
SELECT id, action_id, payload, attempts, next_attempt, delivered_at, last_error, created_at
FROM outcome_outbox
WHERE delivered_at IS NULL AND next_attempt <= ?
ORDER BY next_attempt
LIMIT ?
`

type NextOutcomeBatchParams struct {
	NextAttempt string `json:"next_attempt"`
	Limit       int64  `json:"limit"`
}

func (q *Queries) NextOutcomeBatch(ctx context.Context, arg NextOutcomeBatchParams) ([]OutcomeOutbox, error) {
	rows, err := q.db.QueryContext(ctx, nextOutcomeBatch, arg.NextAttempt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutcomeOutbox
	for rows.Next() {
		var i OutcomeOutbox
		if err := rows.Scan(
			&i.ID,
			&i.ActionID,
			&i.Payload,
			&i.Attempts,
			&i.NextAttempt,
			&i.DeliveredAt,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putActionResult = `-- name: PutActionResult :exec
UPDATE actions SET status = ?, result = ?, error = ?, completed_at = ?, updated_at = ? WHERE id = ?
`

type PutActionResultParams struct {
	Status      string         `json:"status"`
	Result      sql.NullString `json:"result"`
	Error       sql.NullString `json:"error"`
	CompletedAt sql.NullString `json:"completed_at"`
	UpdatedAt   string         `json:"updated_at"`
	ID          string         `json:"id"`
}

func (q *Queries) PutActionResult(ctx context.Context, arg PutActionResultParams) error {
	_, err := q.db.ExecContext(ctx, putActionResult,
		arg.Status,
		arg.Result,
		arg.Error,
		arg.CompletedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const rememberIdempotency = `-- name: RememberIdempotency :exec
INSERT INTO idempotency_keys (key, action_id, result, expires_at, created_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(key) DO UPDATE SET
    action_id  = excluded.action_id,
    result     = excluded.result,
    expires_at = excluded.expires_at
`

type RememberIdempotencyParams struct {
	Key       string         `json:"key"`
	ActionID  string         `json:"action_id"`
	Result    string         `json:"result"`
	ExpiresAt sql.NullString `json:"expires_at"`
	CreatedAt string         `json:"created_at"`
}

func (q *Queries) RememberIdempotency(ctx context.Context, arg RememberIdempotencyParams) error {
	_, err := q.db.ExecContext(ctx, rememberIdempotency,
		arg.Key,
		arg.ActionID,
		arg.Result,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const searchAuditEvents = `-- name: SearchAuditEvents :many
SELECT id, action_id, kind, capability, caller_type, detail, created_at
FROM audit_events
WHERE (?1  IS NULL OR capability  = ?1)
  AND (?2 IS NULL OR caller_type = ?2)
  AND (?3     IS NULL OR created_at >= ?3)
  AND (?4       IS NULL OR created_at <= ?4)
ORDER BY created_at
`

type SearchAuditEventsParams struct {
	Capability interface{} `json:"capability"`
	CallerType interface{} `json:"caller_type"`
	FromTs     interface{} `json:"from_ts"`
	ToTs       interface{} `json:"to_ts"`
}

func (q *Queries) SearchAuditEvents(ctx context.Context, arg SearchAuditEventsParams) ([]AuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, searchAuditEvents,
		arg.Capability,
		arg.CallerType,
		arg.FromTs,
		arg.ToTs,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.ActionID,
			&i.Kind,
			&i.Capability,
			&i.CallerType,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateActionStatus = `-- name: UpdateActionStatus :exec
UPDATE actions SET status = ?, updated_at = ? WHERE id = ?
`

type UpdateActionStatusParams struct {
	Status    string `json:"status"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateActionStatus(ctx context.Context, arg UpdateActionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateActionStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}

const upsertAction = `-- name: UpsertAction :exec
INSERT INTO actions (id, capability, payload, caller_type, caller_id, caller_name, scope, idempotency_key, status, result, error, policy_decision, executed_at, completed_at, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    capability      = excluded.capability,
    payload         = excluded.payload,
    caller_type     = excluded.caller_type,
    caller_id       = excluded.caller_id,
    caller_name     = excluded.caller_name,
    scope           = excluded.scope,
    idempotency_key = excluded.idempotency_key,
    status          = excluded.status,
    result          = excluded.result,
    error           = excluded.error,
    policy_decision = excluded.policy_decision,
    executed_at     = excluded.executed_at,
    completed_at    = excluded.completed_at,
    updated_at      = excluded.updated_at
`

type UpsertActionParams struct {
	ID             string         `json:"id"`
	Capability     string         `json:"capability"`
	Payload        string         `json:"payload"`
	CallerType     string         `json:"caller_type"`
	CallerID       string         `json:"caller_id"`
	CallerName     string         `json:"caller_name"`
	Scope          string         `json:"scope"`
	IdempotencyKey string         `json:"idempotency_key"`
	Status         string         `json:"status"`
	Result         sql.NullString `json:"result"`
	Error          sql.NullString `json:"error"`
	PolicyDecision sql.NullString `json:"policy_decision"`
	ExecutedAt     sql.NullString `json:"executed_at"`
	CompletedAt    sql.NullString `json:"completed_at"`
	CreatedAt      string         `json:"created_at"`
	UpdatedAt      string         `json:"updated_at"`
}

func (q *Queries) UpsertAction(ctx context.Context, arg UpsertActionParams) error {
	_, err := q.db.ExecContext(ctx, upsertAction,
		arg.ID,
		arg.Capability,
		arg.Payload,
		arg.CallerType,
		arg.CallerID,
		arg.CallerName,
		arg.Scope,
		arg.IdempotencyKey,
		arg.Status,
		arg.Result,
		arg.Error,
		arg.PolicyDecision,
		arg.ExecutedAt,
		arg.CompletedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertCapability = `-- name: UpsertCapability :exec
INSERT INTO capabilities (name, description, input_schema, output_schema, permissions, simulatable, idempotent, registered_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(name) DO UPDATE SET
    description   = excluded.description,
    input_schema  = excluded.input_schema,
    output_schema = excluded.output_schema,
    permissions   = excluded.permissions,
    simulatable   = excluded.simulatable,
    idempotent    = excluded.idempotent,
    registered_at = excluded.registered_at
`

type UpsertCapabilityParams struct {
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	InputSchema  string         `json:"input_schema"`
	OutputSchema string         `json:"output_schema"`
	Permissions  string         `json:"permissions"`
	Simulatable  int64          `json:"simulatable"`
	Idempotent   int64          `json:"idempotent"`
	RegisteredAt string         `json:"registered_at"`
}

func (q *Queries) UpsertCapability(ctx context.Context, arg UpsertCapabilityParams) error {
	_, err := q.db.ExecContext(ctx, upsertCapability,
		arg.Name,
		arg.Description,
		arg.InputSchema,
		arg.OutputSchema,
		arg.Permissions,
		arg.Simulatable,
		arg.Idempotent,
		arg.RegisteredAt,
	)
	return err
}

const upsertPolicyRule = `-- name: UpsertPolicyRule :exec
INSERT INTO policy_rules (id, capability, caller_type, scope, decision, reason, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    capability  = excluded.capability,
    caller_type = excluded.caller_type,
    scope       = excluded.scope,
    decision    = excluded.decision,
    reason      = excluded.reason,
    updated_at  = excluded.updated_at
`

type UpsertPolicyRuleParams struct {
	ID         string         `json:"id"`
	Capability sql.NullString `json:"capability"`
	CallerType sql.NullString `json:"caller_type"`
	Scope      string         `json:"scope"`
	Decision   string         `json:"decision"`
	Reason     sql.NullString `json:"reason"`
	CreatedAt  string         `json:"created_at"`
	UpdatedAt  string         `json:"updated_at"`
}

func (q *Queries) UpsertPolicyRule(ctx context.Context, arg UpsertPolicyRuleParams) error {
	_, err := q.db.ExecContext(ctx, upsertPolicyRule,
		arg.ID,
		arg.Capability,
		arg.CallerType,
		arg.Scope,
		arg.Decision,
		arg.Reason,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
